export const current_projects = [
    {
        link: 'https://google.com',
        title: '2Unstoppable',
        date: '2022',
        summary: 'Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan.',
        image: 'https://plugins.jetbrains.com/files/16260/113019/icon/pluginIcon.png',
        altText: 'Image for Featured Project 1',
    },
    {
        link: 'https://google.com',
        title: 'YKNOT',
        date: '2022',
        summary: 'Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan.',
        image: 'https://plugins.jetbrains.com/files/16260/113019/icon/pluginIcon.png',
        altText: 'Image for Featured Project 2',
    },
    {
        link: 'https://google.com',
        title: 'Matt Haven Fridge',
        date: '2022',
        summary: 'Short summary about the project. ',
        image: 'https://plugins.jetbrains.com/files/16260/113019/icon/pluginIcon.png',
        altText: 'Image for Featured Project 3',
    },
    {
        link: 'https://google.com',
        title: 'Project 4',
        date: '2022',
        summary: 'Short summary about the project. ',
        image: 'https://plugins.jetbrains.com/files/16260/113019/icon/pluginIcon.png',
        altText: 'Image for Featured Project 4',
    },
    {
        link: 'https://google.com',
        title: 'Project 5',
        date: '2022',
        summary: 'Short summary about the project. ',
        image: 'https://plugins.jetbrains.com/files/16260/113019/icon/pluginIcon.png',
        altText: 'Image for Featured Project 5',
    },
    {
        link: 'https://google.com',
        title: 'Project 6',
        date: '2022',
        summary: 'Short summary about the project. ',
        image: 'https://plugins.jetbrains.com/files/16260/113019/icon/pluginIcon.png',
        altText: 'Image for Featured Project 5',
    }
]