export const past_projects = [
    {
        link: 'https://google.com',
        title: '2Unstoppable',
        date: '2022',
        summary: 'Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan.',
        image: 'https://plugins.jetbrains.com/files/16260/113019/icon/pluginIcon.png',
        altText: 'Image for Project 1',
        org: '2Unstoppable',
        team: ['John Doe', 'Jane Doe', 'Joe Doe'],
    },
    {
        link: 'https://google.com',
        title: 'YKNOT',
        date: '2022',
        summary: 'Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan.',
        image: 'https://plugins.jetbrains.com/files/16260/113019/icon/pluginIcon.png',
        altText: 'Image for Project 2',
        org: 'YKNOT',
        team: ['Adam Anderson', 'Bob Bobson', 'Carlos Carlos'],
    },
    {
        link: 'https://google.com',
        title: 'Matt Haven Fridge',
        date: '2022',
        summary: 'Short summary about the project. ',
        image: 'https://plugins.jetbrains.com/files/16260/113019/icon/pluginIcon.png',
        altText: 'Image for Project 3',
        org: 'Matt Haven Fridge',
        team: ['John Doe', 'Adam Anderson', 'Doug Dougson'],
    },
    {
        link: 'https://google.com',
        title: 'Organization 4',
        date: '2022',
        summary: 'Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan.',
        image: 'https://plugins.jetbrains.com/files/16260/113019/icon/pluginIcon.png',
        altText: 'Image for Project 4',
        org: 'Wendys',
        team: ['John Doe', 'Adam Anderson', 'Doug Dougson'],
    },
    {
        link: 'https://google.com',
        title: 'The Organization 5',
        date: '2022',
        summary: 'Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan.',
        image: 'https://plugins.jetbrains.com/files/16260/113019/icon/pluginIcon.png',
        altText: 'Image for Project 5',
        org: 'University of Maryland',
        team: ['Doug Dougson', 'Eric Yi', 'Jane Doe', 'Adam Anderson'],
    },
    {
        link: 'https://google.com',
        title: "Revamping CORA's Website",
        date: '2021',
        summary: 'Short summary about the project.',
        image: 'https://plugins.jetbrains.com/files/16260/113019/icon/pluginIcon.png',
        altText: 'Image for Project 6',
        org: 'CORA',
        team: ['Eric Yi', 'Bob Bobson'],
    },
    {
        link: 'https://google.com',
        title: 'Coding Project 7',
        date: '2021',
        summary: 'Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan.',
        image: 'https://plugins.jetbrains.com/files/16260/113019/icon/pluginIcon.png',
        altText: 'Image for Project 7',
        org: 'Hack4Impact',
        team: ['Eric Yi', 'Adam Anderson', 'Bob Bobson', 'Carlos Carlos','Doug Dougson'],
    },
    {
        link: 'https://google.com',
        title: 'Project 8',
        date: '2021',
        summary: 'Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan. Short summary about the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit velit in vitae diam ut blandit accumsan.',
        image: 'https://plugins.jetbrains.com/files/16260/113019/icon/pluginIcon.png',
        altText: 'Image for Project 8',
        org: 'Hack4Impact',
        team: ['Eric Yi'],
    },
    {
        link: 'https://google.com',
        title: 'A Project for the Future 9',
        date: '2021',
        summary: 'Short summary about the project. ',
        image: 'https://plugins.jetbrains.com/files/16260/113019/icon/pluginIcon.png',
        altText: 'Image for Project 10',
        org: 'University of Maryland',
        team: ['Eric Ericson'],
    }
]